# Build Specification for AWS CodeBuild
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

version: 0.1
phases:
  pre_build:
    commands:
    - "echo Logging in to Amazon ECR..."
    - "$(aws ecr get-login --no-include-email --region us-east-2)"
  build:
    commands:
    - "echo Passing the tests..."
    - "sbt test"
    - "echo Building the Docker image..."
    - "docker build -t test-project ."
    - "docker tag test-project:latest 877899260343.dkr.ecr.us-east-2.amazonaws.com/test-project:latest"
  post_build:
    commands:
    - "echo Pushing the Docker image..."
    - "docker push 877899260343.dkr.ecr.us-east-2.amazonaws.com/test-project:latest"